[package]
name = "async-io"
# When publishing a new version:
# - Update CHANGELOG.md
# - Create "v1.x.y" git tag
version = "1.6.0"
authors = ["Stjepan Glavina <stjepang@gmail.com>"]
edition = "2018"
rust-version = "1.46"
description = "Async I/O and timers"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/smol-rs/async-io"
homepage = "https://github.com/smol-rs/async-io"
documentation = "https://docs.rs/async-io"
keywords = ["mio", "epoll", "kqueue", "iocp", "wepoll"]
categories = ["asynchronous", "network-programming", "os"]
exclude = ["/.*"]

[dependencies]
concurrent-queue = "1.2.2"
futures-lite = "1.11.0"
log = "0.4.11"
once_cell = "1.4.1"
parking = "2.0.0"
polling = "2.0.0"
slab = "0.4.2"
socket2 = { version = "0.4.2", features = ["all"] }
waker-fn = "1.1.0"

[target."cfg(unix)".dependencies]
libc = "0.2.77"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.9", features = ["winsock2"] }

[dev-dependencies]
env_logger = "*"
async-channel = "1.4.2"
async-net = "1.3.0"
blocking = "1.0.0"
signal-hook = "0.3"
tempfile = "3.1.0"
#test-env-log = "0.2.8"
humantime = "*"

[target.'cfg(target_os = "linux")'.dev-dependencies]
inotify = { version = "0.10", default-features = false }
nix = "0.23"
timerfd = "1.1.1"

[target.'cfg(windows)'.dev-dependencies]
uds_windows = "1"

[patch.crates-io]
#netlink-proto = { git = "https://github.com/winksaville/netlink", tag = "Add-debug-v4" }
polling = { git = "https://github.com/winksaville/polling", tag = "Add-debug-v6" }
#async-io = { git = "https://github.com/winksaville/async-io", tag = "Add-debug-v11" }
